import type { InsightItem } from "./types";

export const placeholderInsights: InsightItem[] = [
  {
    id: 1,
    type: "Video",
    title: "How to read a research call before you act",
    summary: "A quick walkthrough of targets, stop-loss levels, time horizons, and risk notes.",
    category: "Getting started",
    author: "Tarkashh Learning",
    publishedAt: "Today",
    duration: "6 min watch",
    accent: "#5271FF",
  },
  {
    id: 2,
    type: "Article",
    title: "Five questions to ask before following an analyst",
    summary: "Use a repeatable checklist to compare research styles and choose analysts that fit your goals.",
    category: "Investor basics",
    author: "Tarkashh Editorial",
    publishedAt: "2 days ago",
    duration: "5 min read",
    accent: "#16A36A",
  },
  {
    id: 3,
    type: "Article",
    title: "Understanding risk-to-reward in simple terms",
    summary: "Learn what the ratio shows, where it helps, and why it should not be used on its own.",
    category: "Risk management",
    author: "Tarkashh Editorial",
    publishedAt: "4 days ago",
    duration: "7 min read",
    accent: "#F59E0B",
  },
  {
    id: 4,
    type: "Video",
    title: "Building a balanced watchlist",
    summary: "See how sectors, market caps, and time horizons can be organised in one clear watchlist.",
    category: "Portfolio habits",
    author: "Tarkashh Learning",
    publishedAt: "1 week ago",
    duration: "9 min watch",
    accent: "#8B5CF6",
  },
  {
    id: 5,
    type: "Article",
    title: "Why call outcomes need context",
    summary: "A practical guide to reviewing open, target-hit, and stop-loss outcomes without cherry-picking.",
    category: "Performance",
    author: "Tarkashh Editorial",
    publishedAt: "1 week ago",
    duration: "6 min read",
    accent: "#0EA5E9",
  },
  {
    id: 6,
    type: "Video",
    title: "Using your recommendation filters",
    summary: "Find calls from a particular analyst, segment, status, or date range in a few clicks.",
    category: "Product guide",
    author: "Tarkashh Learning",
    publishedAt: "2 weeks ago",
    duration: "4 min watch",
    accent: "#EC4899",
  },
];
